import { slugField } from "@/fields/slug";
import { CollectionConfig } from "payload";

const AutoGeneratedConferences: CollectionConfig = {
  slug: 'auto-generated-conferences',
  admin: {
    useAsTitle: 'title',
  },
  access: {
    // read: ({ req }) => !!req.user,
    // create: ({ req }) => !!req.user,
    // update: ({ req }) => !!req.user,
    // delete: ({ req }) => !!req.user,
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
    },
    ...slugField(),
    {
      name: 'dateFormat',
      type: 'text',
      required: true,
      admin: {
        description: 'Date in string format'
      }
    },
    {
      name : 'user',
      type : 'relationship',
      relationTo : 'users'
    }
  ],
  hooks : {
    beforeChange: [
      async ({ req, data, operation }) => {
        // Auto-assign user on create
        if (operation === 'create' && req.user) {
          data.user = req.user.id;
        }
        return data;
      }
    ],
  }
};

export default AutoGeneratedConferences;