import { findAllAutoGeneratedConferences } from "@/features/auto-generated-conferences/actions"
import ListAutoGeneratedConferences from "@/features/auto-generated-conferences/components/list-auto-generated-conferences"
import isPageCanBeAccessed from "@/utilities/protectPageUtils";
import { Plus } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";

export default async function Page() {
    if(! (await isPageCanBeAccessed())) {
        redirect("/auth")
    }

    const conferencesDocs = await findAllAutoGeneratedConferences();

    return <div className="flex flex-col w-full h-full mx-auto container">
        <div className="flex flex-row justify-between items-center py-4">
            <p>Auto Generated Conferences</p>
            <Link href={"auto-conferences/create"} className="bg-blue-600 hover:bg-blue-500 px-6 py-2 rounded-lg flex items-center justify-center text-white">
                <Plus className="w-5 h-5" />
                Create
            </Link>
        </div>
        <ListAutoGeneratedConferences docs={conferencesDocs} />
    </div>
}